name: Docker

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: setup node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: setup dotnet8
      uses: actions/setup-dotnet@v2
      env:
          GITHUB_TOKEN: '${{ secrets.ACTIONS_TOKEN }}'
      with:
        dotnet-version: 8.0.x
        
    - name: restore projects
      run: 
        dotnet restore ./fnpackup
        
    - name: docker login
      uses: docker/login-action@v2.1.0
      with:
        username: '${{secrets.DOCKER_USERNAME}}'
        password: '${{secrets.DOCKER_PASSWORD}}'
    
    - name: docker buildx
      uses: docker/setup-buildx-action@v2.5.0
    
    - name: sed shell
      run:  sed -i 's/\r$//' ./shells/publish-docker.sh
    - name: chmod shell
      run: chmod +x ./shells/publish-docker.sh
    - name: publish projects
      run: ./shells/publish-docker.sh

    - name: create docker image manifest
      run: |
        docker pull --platform linux/arm/v7 snltty/fnpackup-musl-arm:latest &&  \
        docker tag snltty/fnpackup-musl-arm:latest snltty/fnpackup-musl:arm &&  \
        docker push snltty/fnpackup-musl:arm &&  \
        docker pull --platform linux/arm64 snltty/fnpackup-musl-arm64:latest &&  \
        docker tag snltty/fnpackup-musl-arm64:latest snltty/fnpackup-musl:arm64 &&  \
        docker push snltty/fnpackup-musl:arm64 &&  \
        docker pull --platform linux/amd64 snltty/fnpackup-musl-x64:latest &&  \
        docker tag snltty/fnpackup-musl-x64:latest snltty/fnpackup-musl:amd64 &&  \
        docker push snltty/fnpackup-musl:amd64 &&  \
        docker manifest create snltty/fnpackup-musl:latest snltty/fnpackup-musl:amd64 snltty/fnpackup-musl:arm64 snltty/fnpackup-musl:arm && \
        docker manifest create snltty/fnpackup-musl:v{{version}} snltty/fnpackup-musl:amd64 snltty/fnpackup-musl:arm64 snltty/fnpackup-musl:arm && \
        docker manifest push snltty/fnpackup-musl:latest && \
        docker manifest push snltty/fnpackup-musl:v{{version}}